version: '3'
services:
  #  Create a service named db.
  db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: 'postgres'

    #   Give the container the name my_postgres.

    container_name: 'postgres-db'
    #   Setup the username, password, and database name.

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EndpointChallenge

    #   Maps port 5432 (localhost) to port 5432 on the container.
    expose:
      - 5432

    ports:
      - 5432:5432

    #   Set a volume some that database is not lost after shutting down the container.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  #  Create a service named nest-api.
  nest-api:
    # Name of image created before
    image: nest-api

    container_name: nest-api

    restart: always

    expose:
      - 3000

    ports:
      - '3000:3000'
